## numpy Go

In [158]:
import numpy as np

my_list = list(range(100)) 
my_array = np.arange(100)

In [164]:
%timeit my_list2 = [i *2 for i in my_list]
%timeit my_array2 = my_array * 2

948 ns ± 1.62 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [169]:
a =[
[1, 1.2, 3],
    [-123, 123, 0]
]
data = np.array(a)
print(data)

#넘파이배열로 변환


[[   1.     1.2    3. ]
 [-123.   123.     0. ]]


In [13]:
# 0차원 : 스칼라(scala), 1차원 : 벡터(vector), 
# 2차원 : 행렬(matrix), 3차원 : 텐서(tenser)
print(data * 10)
print(data + data)

[[   10.    12.    30.]
 [-1230.  1230.     0.]]
[[   2.     2.4    6. ]
 [-246.   246.     0. ]]


In [170]:
print(data.shape)
print(data.dtype)
print(type(data))


#shape 몇행 몇 열인지, (2(행),3(열))
# numpy는 배열을 다룸. dtype은 하나하나의 요소를 설명함

(2, 3)
float64
<class 'numpy.ndarray'>


## ndarray 

In [171]:
data1 = [1, 2, 3, 4, 5]
arr1 = np.array(data1)
print(arr1)
print(type(arr1))
print(arr1.dtype)
#궁금증 data = np.array(a) -> 
# print(data.dtype)
# = float
#

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64


In [21]:
arr2 = np.array([[1.1, 2.2],[3.3, 4.4]])
print(arr2)
print(type(arr2))

# 데이터 구성이 딱 맞아야함 X ([1.1], [2.2, 3.3]) X

[[1.1 2.2]
 [3.3 4.4]]
<class 'numpy.ndarray'>


In [24]:
print(arr1.ndim)
print(arr2.ndim)

# 아마 배열이 몇 차원인지?

1
2


In [25]:
print(arr1.shape)
print(arr2.shape)

# 각 배열에 요소 개수

(5,)
(2, 2)


In [182]:
print(np.zeros(10))
#print([0] * 10)
print(np.zeros((4, 4)))
print(np.empty((2, 2, 2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [32]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


## ndarray 자료형

In [35]:
arr1 = np.array([1, 2, 3], dtype = np.float64)
arr2 = np.array([1, 2, 3], dtype = np.int32)

print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [39]:
arr1 = np.array([1, 2, 3])
print(arr1.dtype)
float_arr1 = arr1.astype(np.float64)
print(float_arr1)
print(float_arr1.dtype)

int64
[1. 2. 3.]
float64


In [43]:
arr2 = np.array([1.1, 2.2, 3.3])
print(arr2.dtype)
int_arr2 = arr2.astype(np.int64)
print(int_arr2)
print(int_arr2.dtype)

float64
[1 2 3]
int64


## 산술 연산

In [51]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr * arr)
print(arr + arr)
print(1 / arr)
print(arr ** 3)

# 지 값을 여러번 계산함

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[ 2  4  6]
 [ 8 10 12]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[  1   8  27]
 [ 64 125 216]]


In [56]:
arr2 = np.array([[3, 2, 1],[1, 2, 3]])
print(arr)
print(arr2)
print(arr > arr2)
print(arr == 3)

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [1 2 3]]
[[False False  True]
 [ True  True  True]]
[[False False  True]
 [False False False]]


## 색인과 슬라이싱

In [184]:
arr =  np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [185]:
print(arr[7])
print(arr[2:5])
arr[7]

7
[2 3 4]


np.int64(7)

In [186]:
arr[2:5] = 10
print(arr)
#파이썬은 안되는데 넘파이는 값 수정이 된다. 

[ 0  1 10 10 10  5  6  7  8  9]


In [190]:
py_list = [1, 2, 3, 4, 5]
py_list[2:3].pop()
#파이썬은 원본을 그대로 사용한다. 지금까지 한 것 1차원 배
# [2:3]은 앞에거 가져오고 뒤에거 안가져옴

3

In [189]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

#1,2,3은 0번째 데이터

[[1 2 3]
 [4 5 6]]


In [77]:
print(arr[1])
print(arr[1][1])
print(arr[1, 1])

[4 5 6]
5
5


In [87]:
arr3d = np.array([[[1,2,3],[4,5,6],[7,8,9]],
                   [[11,12,13],[14,15,16],[17,18,19]],
                   [[11,22,33],[44,55,66],[77,88,99]]])

#3번째 행, 첫번째 배열, 두번째 데이터임.

In [88]:
print(arr3d[2][0][1])
print(arr3d[2,0,1])

22
22


In [99]:
arr3d[:1, 1:, 2:]

##이해함 근데 한번 더해야함.

array([[[6],
        [9]]])

In [191]:
arr3d[:1, 1:, 2:]= 9999
print(arr3d)

#그 찾은 값 안해 9999를 넣으면 된다는 뜻

[[[   1    2    3]
  [   4    5 9999]
  [   7    8 9999]]

 [[  11   12   13]
  [  14   15   16]
  [  17   18   19]]

 [[  11   22   33]
  [  44   55   66]
  [  77   88   99]]]


## 불리언 값으로 선택

In [93]:
names = np.array(['hong', 'kim', 'hong', 'kim'])
data = np.array([['math', 60],['math', 90],['eng',70],['eng', 50]])

In [94]:
names == 'hong'

array([ True, False,  True, False])

In [96]:
data[True, False, True, False]
data[names == 'hong']
#특정 조건에 맞는 데이터 고를때 사용

array([['math', '60'],
       ['eng', '70']], dtype='<U21')

In [98]:
print(data[names == 'hong', 1])
print(data[names == 'hong', :1])

['60' '70']
[['math']
 ['eng']]


In [101]:
names != 'hong'

array([False,  True, False,  True])

In [102]:
print(names != 'hong')
print(~(names == 'hong'))

[False  True False  True]
[False  True False  True]


In [103]:
cond = names == 'kim'
data[cond]

array([['math', '90'],
       ['eng', '50']], dtype='<U21')

## 팬시 색인 (fancy indexing)

In [108]:
arr = np.zeros((8,4))
for i in range(8):
    arr[i] = i
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [109]:
arr[[4, 3, 0, 5]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [5., 5., 5., 5.]])

In [110]:
arr[[-3, -5, -1]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [7., 7., 7., 7.]])

In [194]:
arr = np.arange(32).reshape(8, 4) # 8개의 set, 4개의 요소
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [196]:
arr[[1, 5]][:,[2,3]]

array([[ 6,  7],
       [22, 23]])

In [198]:
arr[[1, 5], [2, 3]]

array([ 6, 23])

## 배열 전치

In [131]:
arr = np.arange(15).reshape(3, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [132]:
print(arr.T)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [135]:
# 행렬의 내적, 곱
print(arr @ arr.T)
print(np.dot(arr,arr.T))

[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


## numpy 함수

In [151]:
samples = np.random.standard_normal(size=(3, 3))
print(samples)

[[ 0.23243703 -0.665715    0.02550846]
 [ 1.37401278 -1.07044899 -2.78261187]
 [ 0.66848967  0.44866926 -0.07283804]]


In [152]:
arr1 = np.sqrt(samples)
print(arr1)
#nan = not a number, 결측치

[[0.48211723        nan 0.15971368]
 [1.17218291        nan        nan]
 [0.81761218 0.66982778        nan]]


/var/folders/0n/1bq7yv2110n08vgc04jsftjh0000gn/T/ipykernel_23552/427227.py:1: RuntimeWarning: invalid value encountered in sqrt
  arr1 = np.sqrt(samples)


In [153]:
arr2 = np.abs(samples)
print(arr2)
#abs = absolute 절댓값

[[0.23243703 0.665715   0.02550846]
 [1.37401278 1.07044899 2.78261187]
 [0.66848967 0.44866926 0.07283804]]


In [154]:
np.isnan(arr1)

array([[False,  True, False],
       [False,  True,  True],
       [False, False,  True]])