In [3]:
import numpy as np
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [2]:
import pandas as pd
import seaborn as sns

In [6]:
df = sns.load_dataset('taxis')
df.head

<bound method NDFrame.head of                   pickup             dropoff  passengers  distance  fare  \
0    2019-03-23 20:21:09 2019-03-23 20:27:24           1      1.60   7.0   
1    2019-03-04 16:11:55 2019-03-04 16:19:00           1      0.79   5.0   
2    2019-03-27 17:53:01 2019-03-27 18:00:25           1      1.37   7.5   
3    2019-03-10 01:23:59 2019-03-10 01:49:51           1      7.70  27.0   
4    2019-03-30 13:27:42 2019-03-30 13:37:14           3      2.16   9.0   
...                  ...                 ...         ...       ...   ...   
6428 2019-03-31 09:51:53 2019-03-31 09:55:27           1      0.75   4.5   
6429 2019-03-31 17:38:00 2019-03-31 18:34:23           1     18.74  58.0   
6430 2019-03-23 22:55:18 2019-03-23 23:14:25           1      4.14  16.0   
6431 2019-03-04 10:09:25 2019-03-04 10:14:29           1      1.12   6.0   
6432 2019-03-13 19:31:22 2019-03-13 19:48:02           1      3.85  15.0   

       tip  tolls  total   color      payment            

In [105]:
df = sns.load_dataset('penguins')
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

In [106]:
df.info

<bound method DataFrame.info of     species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
3    Adelie  Torgersen             NaN            NaN                NaN   
4    Adelie  Torgersen            36.7           19.3              193.0   
..      ...        ...             ...            ...                ...   
339  Gentoo     Biscoe             NaN            NaN                NaN   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    Male  
1

In [107]:
cond = df['body_mass_g'] >= 5000

In [108]:
penguins['body_mass_g'] >= 5000
cond1 = penguins.sort_values(['body_mass_g'], ascending=[False]).head(10)

NameError: name 'penguins' is not defined

In [109]:
df.loc[cond1].head(63)

Empty DataFrame
Columns: [species, island, bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g, sex]
Index: []

In [110]:
# Gentoo종의 flipper_length 평균

#일단, 젠투종을 골라내야겠지
#그 다음, 플리퍼 길이의 평균을 구하면 되겠다!

In [111]:
cond1 = df['species'] == 'Gentoo'

In [112]:
df.loc[cond1, 'flipper_length_mm'].mean()

np.float64(217.1869918699187)

In [113]:
# Female Chinstrap종의 bill_length 높은순 정렬

In [114]:
cond2 = df['species'] == 'Chinstrap'

In [115]:
cond3 = df['sex'] == 'Female'

In [116]:
cond4 = df.sort_values('bill_length_mm', ascending=False).head()

In [117]:
df.loc[cond2 & cond3].sort_values('bill_length_mm', ascending=False).head(10)

species island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
169  Chinstrap  Dream            58.0           17.8              181.0   
196  Chinstrap  Dream            50.9           17.9              196.0   
178  Chinstrap  Dream            50.5           18.4              200.0   
219  Chinstrap  Dream            50.2           18.7              198.0   
198  Chinstrap  Dream            50.1           17.9              190.0   
201  Chinstrap  Dream            49.8           17.3              198.0   
202  Chinstrap  Dream            48.1           16.4              199.0   
188  Chinstrap  Dream            47.6           18.3              195.0   
187  Chinstrap  Dream            47.5           16.8              199.0   
164  Chinstrap  Dream            47.0           17.3              185.0   

     body_mass_g     sex  
169       3700.0  Female  
196       3675.0  Female  
178       3400.0  Female  
219       3775.0  Female  
198       3400.0  Female  
201       3675.0  Female  
202       3325.0  Female  
188       3850.0  Female  
187       3900.0  Female  
164       3700.0  Female

In [118]:
# species(종)별 성별 구분하여 평균 몸무게 출력
# => ex) Adelie, Female / Adelie, male / Gentoo, Female...

In [119]:
cond1 = df['species'] == 'Adelie'
cond2 = df['sex'] == 'Female'

In [120]:
cond3 = df['species'] == 'Male'

In [121]:
df.loc[cond1 & cond2, 'body_mass_g'].mean()

np.float64(3368.8356164383563)

In [122]:
# bill_depth 결측치 채우기
# => 같은종 같은섬의 평균으로

In [123]:
df['species'].astype('category').head()

0    Adelie
1    Adelie
2    Adelie
3    Adelie
4    Adelie
Name: species, dtype: category
Categories (3, object): ['Adelie', 'Chinstrap', 'Gentoo']

In [131]:
df['island'].astype('category').head()

0    Torgersen
1    Torgersen
2    Torgersen
3    Torgersen
4    Torgersen
Name: island, dtype: category
Categories (3, object): ['Biscoe', 'Dream', 'Torgersen']

In [147]:
df = sns.load_dataset('penguins')

In [153]:
species1 = df['species'] == 'Adelie'
species2 = df['species'] == 'Chinstrap'
species3 = df['species'] == 'Gentoo'

In [158]:
island1 = df['island'] == 'Biscoe'
island2 = df['island'] == 'Dream'
island3 = df['island'] == 'Torgersen'

In [155]:
bill_depth_mean = df.loc[species1 & island3, 'bill_depth_mm'].mean()

In [156]:
df.loc[species1 & island3, 'bill_depth_mm'] = df.loc[species1 & island3,'bill_depth_mm'].fillna(bill_depth_mean)

In [157]:
df

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1      18.700000              181.0   
1    Adelie  Torgersen            39.5      17.400000              186.0   
2    Adelie  Torgersen            40.3      18.000000              195.0   
3    Adelie  Torgersen             NaN      18.429412                NaN   
4    Adelie  Torgersen            36.7      19.300000              193.0   
..      ...        ...             ...            ...                ...   
339  Gentoo     Biscoe             NaN            NaN                NaN   
340  Gentoo     Biscoe            46.8      14.300000              215.0   
341  Gentoo     Biscoe            50.4      15.700000              222.0   
342  Gentoo     Biscoe            45.2      14.800000              212.0   
343  Gentoo     Biscoe            49.9      16.100000              213.0   

     body_mass_g     sex  
0         3750.0    Male  
1         3800.0  Female  
2         3250.0  Female  
3            NaN     NaN  
4         3450.0  Female  
..           ...     ...  
339          NaN     NaN  
340       4850.0  Female  
341       5750.0    Male  
342       5200.0  Female  
343       5400.0    Male  

[344 rows x 7 columns]